// styles/homeStyles.js

export const homeStyles = {
  body: {
    margin: 0,
    background: 'linear-gradient(180deg, #0b1550 0%, #1e4fb1 55%, #0f1b3a 100%)',
    color: 'white',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    minHeight: '100vh',
  },

  // Top nav
  topNav: {
    background: 'rgba(15, 23, 42, 0.8)',
    backdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(59, 130, 246, 0.2)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navContainer: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    fontSize: '28px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    textDecoration: 'none',
    color: 'white',
  },
  navLinks: {
    display: 'flex',
    gap: '30px',
    alignItems: 'center',
  },
  navLink: {
    color: '#94a3b8',
    textDecoration: 'none',
    fontSize: '16px',
    transition: 'color 0.3s ease',
    cursor: 'pointer',
  },
  uploadButton: {
    background: 'linear-gradient(135deg, #ef4444 0%, #f97316 100%)',
    color: 'white',
    border: 'none',
    padding: '10px 24px',
    borderRadius: '25px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: '0 4px 15px rgba(239, 68, 68, 0.3)',
  },
  signInButton: {
    background: 'transparent',
    border: '1px solid rgba(59, 130, 246, 0.5)',
    color: '#60a5fa',
    padding: '10px 24px',
    borderRadius: '25px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
headline: {
  fontSize: '56px',
  fontWeight: 'bold',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '10px',
  marginBottom: '15px',
},
  // Layout containers
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #0b1550 0%, #1e4fb1 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    textAlign: 'center',
    padding: '40px 20px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  cubeCircle: {
  width: '160px',
  height: '160px',
  borderRadius: '50%',
  backgroundColor: 'rgba(8,20,53,0.35)',
  boxShadow: 'inset 0 0 60px rgba(56,189,248,.15), 0 10px 40px rgba(56,189,248,.18)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  marginBottom: '30px',
  overflow: 'hidden',          // ensures “no escape”
},
  headline: {
    fontSize: '48px',
    fontWeight: 'bold',
    marginBottom: '15px',
  },
  subHeadline: {
    fontSize: '18px',
    opacity: 0.8,
    marginBottom: '25px',
  },
  buttonRow: {
    display: 'flex',
    gap: '20px',
    justifyContent: 'center',
  },
  button: {
    padding: '12px 24px',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    border: 'none',
  },
  demoButton: {
    backgroundColor: '#0ea5e9', // sky blue
    color: 'white',
  },
  trialButton: {
    background: 'linear-gradient(to right, #f97316, #ec4899)', // orange→pink
    color: 'white',
  },
  header: {
    textAlign: 'center',
    marginBottom: '60px',
  },
  heroLogo: {
    fontSize: '56px',
    fontWeight: 'bold',
    marginBottom: '20px',
    background: 'linear-gradient(135deg, #3b82f6, #60a5fa)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  tagline: {
    fontSize: '24px',
    color: '#94a3b8',
    marginBottom: '40px',
  },

  // Main grid + cards
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(380px, 1fr))',
    gap: '30px',
    marginBottom: '60px',
  },
  card: {
    background: 'rgba(30, 41, 59, 0.5)',
    backdropFilter: 'blur(20px)',
    border: '1px solid rgba(59, 130, 246, 0.2)',
    borderRadius: '20px',
    padding: '40px',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    position: 'relative',
    overflow: 'hidden',
  },
  cardHover: {
    transform: 'translateY(-5px)',
    boxShadow: '0 30px 80px rgba(0, 0, 0, 0.4)',
    border: '1px solid rgba(59, 130, 246, 0.4)',
  },
  decorativeGradient: {
    position: 'absolute',
    top: '-50%',
    right: '-50%',
    width: '200%',
    height: '200%',
    background: 'radial-gradient(circle, rgba(59, 130, 246, 0.1) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  iconContainer: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '25px',
    fontSize: '40px',
  },
  watchIcon: {
    background: 'linear-gradient(135deg, #ef4444, #f97316)',
  },
  workIcon: {
    background: 'linear-gradient(135deg, #3b82f6, #60a5fa)',
  },
  hireIcon: {
    background: 'linear-gradient(135deg, #8b5cf6, #a78bfa)',
  },
  cardTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    marginBottom: '15px',
  },
  cardSubtitle: {
    fontSize: '18px',
    color: '#94a3b8',
    marginBottom: '30px',
    lineHeight: '1.6',
  },
  buttonPrimary: {
    background: 'linear-gradient(135deg, #ef4444 0%, #f97316 100%)',
    color: 'white',
    border: 'none',
    padding: '20px 40px',
    borderRadius: '50px',
    fontSize: '18px',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 10px 40px rgba(239, 68, 68, 0.4)',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    justifyContent: 'center',
    width: '100%',
    transition: 'all 0.3s ease',
  },
  features: {
    marginTop: '30px',
    paddingTop: '30px',
    borderTop: '1px solid rgba(59, 130, 246, 0.2)',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    marginBottom: '15px',
    color: '#94a3b8',
    fontSize: '16px',
  },

  // Stats
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '30px',
    marginBottom: '60px',
  },
  statCard: {
    background: 'rgba(30, 41, 59, 0.3)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(59, 130, 246, 0.1)',
    borderRadius: '16px',
    padding: '25px',
    textAlign: 'center',
  },
  statNumber: {
    fontSize: '36px',
    fontWeight: 'bold',
    marginBottom: '8px',
    background: 'linear-gradient(135deg, #3b82f6, #60a5fa)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: '16px',
  },

  // Footer
  footer: {
    background: 'rgba(15, 23, 42, 0.8)',
    backdropFilter: 'blur(20px)',
    borderTop: '1px solid rgba(59, 130, 246, 0.2)',
    marginTop: '100px',
  },
  footerContainer: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '60px 20px',
  },
  footerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '40px',
    marginBottom: '40px',
  },
  footerSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  footerTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
  footerLink: {
    color: '#94a3b8',
    textDecoration: 'none',
    fontSize: '16px',
    transition: 'color 0.3s ease',
    cursor: 'pointer',
  },
  footerBottom: {
    paddingTop: '40px',
    borderTop: '1px solid rgba(59, 130, 246, 0.2)',
    textAlign: 'center',
    color: '#64748b',
  },

  // Mobile menu
  mobileMenuButton: {
    display: 'none',
    background: 'transparent',
    border: 'none',
    color: 'white',
    cursor: 'pointer',
    padding: '10px',
  },
  mobileMenu: {
    position: 'fixed',
    top: 0,
    right: 0,
    width: '300px',
    height: '100vh',
    background: 'rgba(15, 23, 42, 0.95)',
    backdropFilter: 'blur(20px)',
    transform: 'translateX(100%)',
    transition: 'transform 0.3s ease',
    zIndex: 200,
    padding: '20px',
  },
  mobileMenuOpen: {
    transform: 'translateX(0)',
  },
};
